# Generated by Django 5.1.6 on 2025-02-14 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_custom', '0002_rename_cpf_user_nif'),
        ('condominios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Cargo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contratacao', models.CharField(choices=[('TC', 'TC (Termo Certo)'), ('PJ', 'Pessoa Jurídica (PJ)'), ('Estágio', 'Estágio'), ('Tempo Indeterminado', 'Tempo Indeterminado'), ('Temporário', 'Temporário')], default='TC', max_length=20, verbose_name='Tipo de Contratação')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário')),
                ('data_contratacao', models.DateField(verbose_name='Data de Contratação')),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas Extras')),
                ('vales', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Vales')),
                ('remuneracao_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remuneração Adicional')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='funcionarios.cargo')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='condominios.condominio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='auth_custom.user')),
            ],
        ),
    ]
