# Generated by Django 5.1.6 on 2025-02-14 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_custom', '0002_rename_cpf_user_nif'),
        ('condominios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeHabitacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Número da Unidade')),
                ('bloco', models.CharField(blank=True, max_length=20, null=True, verbose_name='Bloco')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='condominios.condominio')),
            ],
            options={
                'verbose_name': 'Unidade Habitacional',
                'verbose_name_plural': 'Unidades Habitacionais',
            },
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Proprietário', 'Proprietário'), ('Inquilino', 'Inquilino')], max_length=20, verbose_name='Status do Morador')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('documento', models.CharField(max_length=14, unique=True, verbose_name='BI/NIF')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moradores', to='condominios.condominio')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='morador', to='auth_custom.user')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moradores', to='moradores.unidadehabitacional')),
            ],
            options={
                'verbose_name': 'Morador',
                'verbose_name_plural': 'Moradores',
            },
        ),
        migrations.AddConstraint(
            model_name='unidadehabitacional',
            constraint=models.UniqueConstraint(fields=('condominio', 'numero', 'bloco'), name='unique_unidade_por_condominio'),
        ),
        migrations.AddConstraint(
            model_name='morador',
            constraint=models.UniqueConstraint(fields=('usuario', 'condominio'), name='unique_morador_por_condominio'),
        ),
    ]
