# Generated by Django 5.1.6 on 2025-02-15 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='documento',
            field=models.CharField(max_length=18, unique=True, verbose_name='BI/NIF'),
        ),
        migrations.CreateModel(
            name='Divida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Dívida')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividas', to='moradores.morador')),
            ],
            options={
                'verbose_name': 'Dívida',
                'verbose_name_plural': 'Dívidas',
                'ordering': ['-data_vencimento'],
            },
        ),
    ]
