# Generated by Django 5.1.6 on 2025-02-14 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_custom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cpf',
            new_name='nif',
        ),
    ]
