# Generated by Django 5.1.6 on 2025-02-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='forma_pagamento',
            field=models.CharField(choices=[('caixa', 'Caixa'), ('banco', 'Banco')], default='banco', max_length=10, verbose_name='Forma de Pagamento'),
        ),
    ]
