# Generated by Django 5.1.6 on 2025-02-14 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_custom', '0002_rename_cpf_user_nif'),
        ('condominios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo de Ocorrência')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data do Comunicado')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados', to='condominios.condominio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados', to='auth_custom.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da Ocorrência')),
                ('resolvido', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='condominios.condominio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='auth_custom.user')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='ocorrencias.tipoocorrencia')),
            ],
        ),
    ]
