# Generated by Django 5.1.6 on 2025-02-14 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_custom', '0002_rename_cpf_user_nif'),
        ('condominios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacoComum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Espaço')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('capacidade', models.IntegerField(default=0, verbose_name='Capacidade Máxima')),
                ('valor_reserva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da Reserva')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacos_comuns', to='condominios.condominio')),
            ],
            options={
                'verbose_name': 'Espaço Comum',
                'verbose_name_plural': 'Espaços Comuns',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateTimeField(verbose_name='Data da Reserva')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Pago')),
                ('comprovativo_pagamento', models.FileField(blank=True, null=True, upload_to='comprovativos/', verbose_name='Comprovativo de Pagamento')),
                ('status', models.CharField(default='pendente', max_length=20, verbose_name='Status da Reserva')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.espacocomum')),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='auth_custom.user')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
